<?php

return [
	'COLUMNS_BD' => [
		'LOWER' => [PDO::ATTR_CASE => PDO::CASE_LOWER],
		'NATURAL' => [PDO::ATTR_CASE => PDO::CASE_NATURAL],
		'UPPER' => [PDO::ATTR_CASE => PDO::CASE_UPPER]
	],
	'RETURN_BD' => [
		'ARRAY' => [PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_BOTH],
		'OBJECT' => [PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ]
	]
];